### ISSUE TITLE
Gateway timeout for nextcloud

### ISSUE THREAD

**Issue by mdhen** [BaptisteBdn/docker-selfhosted-apps#10]
great repo, thanks for making it. I have an issue with nextcloud. I've got traefik, gotify, watchtower and vaultwarden all up and running correctly. Gotify and vaultwarden are accessible via https. I run nextcloud and i just get a gateway timeout when I try to load it via it's subdomain.

logs for the nextcloud container:

> Initializing nextcloud 25.0.2.3 ...
New nextcloud instance
Initializing finished
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.3. Set the 'ServerName' directive globally to suppress this message
[Fri Dec 30 19:47:15.903451 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.1.13 configured -- resuming normal operations
[Fri Dec 30 19:47:15.903537 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

and for traefik:

> time="2022-12-30T19:22:52Z" level=info msg="Configuration loaded from file: /traefik.yml"
> time="2022-12-30T19:22:52Z" level=info msg="Traefik version 2.9.6 built on 2022-12-07T14:17:58Z"
> time="2022-12-30T19:22:52Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
> time="2022-12-30T19:22:52Z" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
> time="2022-12-30T19:22:52Z" level=info msg="Starting provider *file.Provider"
> time="2022-12-30T19:22:52Z" level=info msg="Starting provider *traefik.Provider"
> time="2022-12-30T19:22:52Z" level=info msg="Starting provider *docker.Provider"
> time="2022-12-30T19:22:52Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
> time="2022-12-30T19:22:52Z" level=info msg="Starting provider *acme.Provider"
> time="2022-12-30T19:22:52Z" level=info msg="Testing certificate renew..." ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=mydnschallenge.acme

I've changed the .env files and for traefik the docker-compose.yml and  traefik.yml have been altered so it works with cloudflare.

**Comment by mdhen** [comment]
solved by adding:
> network: proxy

in traefik.yml under providers: docker:

 providers:
   docker:
     endpoint: "tcp://socket-proxy:2375"
     exposedByDefault: false
     network: proxy

**Comment by sutt0n** [comment]
Yep, this fix worked for me as well.

Thank you @mdhen 

Also, adding `'overwriteprotocol' => 'https'` and `'trusted_proxies' => ['<ip of traefik container>']` in Nextcloud's `config/config.php` file fixed iOS connection. Ensure `'trusted_domains'` of your NextCloud domain has `https://` and not `http://`
