### ISSUE TITLE
Fresh install but then errors...

### ISSUE THREAD

**Issue by PLK2** [BaptisteBdn/docker-selfhosted-apps#2]
First of all, thanks for this resource! I've learned a lot trying to get this set up.

I've got Docker Engine and Compose running without issue on RockPro64 / Debian.
I cloned your git repository.
Started by setting up Traefik. Rather than using your "find" command I manually read the .yml and .env files and inputted my information from Namecheap. (I set up API access there).
Then I proceeded to setup the webserver, adjusted the yml and env files, but since then I have not been able to get it to work. Errors thrown. See logs below.
Help, please? And thank you!

time="2022-01-31T12:35:25Z" level=info msg="Configuration loaded from file: /traefik.yml"
time="2022-01-31T12:35:25Z" level=info msg="Traefik version 2.6.0 built on 2022-01-24T17:08:39Z"
time="2022-01-31T12:35:25Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2022-01-31T12:35:25Z" level=info msg="Starting provider aggregator.ProviderAggregator"
time="2022-01-31T12:35:25Z" level=info msg="Starting provider *file.Provider"
time="2022-01-31T12:35:25Z" level=info msg="Starting provider *traefik.Provider"
time="2022-01-31T12:35:25Z" level=info msg="Starting provider *docker.Provider"
time="2022-01-31T12:35:25Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2022-01-31T12:35:25Z" level=info msg="Starting provider *acme.Provider"
time="2022-01-31T12:35:25Z" level=info msg="Testing certificate renew..." providerName=mydnschallenge.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
time="2022-01-31T12:35:28Z" level=error msg="empty args for matcher Host, []" entryPointName=https routerName=webserver@docker
time="2022-01-31T12:35:28Z" level=error msg="Unable to obtain ACME certificate for domains \"\": unable to generate a certificate in ACME provider when no domain is given" routerName=webserver@docker rule="Host(``)" providerName=mydnschallenge.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
time="2022-01-31T12:55:14Z" level=info msg="I have to go..."
time="2022-01-31T12:55:14Z" level=info msg="Stopping server gracefully"
time="2022-01-31T12:55:14Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=https
time="2022-01-31T12:55:14Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=http
time="2022-01-31T12:55:14Z" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=https
time="2022-01-31T12:55:14Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=http
time="2022-01-31T12:55:14Z" level=info msg="Server stopped"
time="2022-01-31T12:55:14Z" level=info msg="Shutting down"
time="2022-01-31T12:55:49Z" level=info msg="Configuration loaded from file: /traefik.yml"
time="2022-01-31T12:55:49Z" level=info msg="Traefik version 2.6.0 built on 2022-01-24T17:08:39Z"
time="2022-01-31T12:55:49Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2022-01-31T12:55:49Z" level=info msg="Starting provider aggregator.ProviderAggregator"
time="2022-01-31T12:55:49Z" level=info msg="Starting provider *file.Provider"
time="2022-01-31T12:55:49Z" level=info msg="Starting provider *traefik.Provider"
time="2022-01-31T12:55:49Z" level=info msg="Starting provider *docker.Provider"
time="2022-01-31T12:55:49Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2022-01-31T12:55:49Z" level=info msg="Starting provider *acme.Provider"
time="2022-01-31T12:55:49Z" level=info msg="Testing certificate renew..." ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=mydnschallenge.acme
time="2022-01-31T13:01:38Z" level=info msg="I have to go..."
time="2022-01-31T13:01:38Z" level=info msg="Stopping server gracefully"
time="2022-01-31T13:01:38Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=https
time="2022-01-31T13:01:38Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=http
time="2022-01-31T13:01:38Z" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=https
time="2022-01-31T13:01:38Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=http
time="2022-01-31T13:01:38Z" level=info msg="Server stopped"
time="2022-01-31T13:01:38Z" level=info msg="Shutting down"
time="2022-01-31T13:01:50Z" level=info msg="Configuration loaded from file: /traefik.yml"
time="2022-01-31T13:01:50Z" level=info msg="Traefik version 2.6.0 built on 2022-01-24T17:08:39Z"
time="2022-01-31T13:01:50Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"https\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"tcp://socket-proxy:2375\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"directory\":\"/rules\",\"watch\":true}},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"certificatesResolvers\":{\"mydnschallenge\":{\"acme\":{\"email\":\"pk3000@protonmail.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"./letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"certificatesDuration\":2160,\"dnsChallenge\":{\"provider\":\"namecheap\",\"delayBeforeCheck\":\"10s\"}}}},\"pilot\":{\"dashboard\":true}}"
time="2022-01-31T13:01:50Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2022-01-31T13:01:50Z" level=info msg="Starting provider aggregator.ProviderAggregator"
time="2022-01-31T13:01:50Z" level=debug msg="Start TCP Server" entryPointName=https
time="2022-01-31T13:01:50Z" level=debug msg="Start TCP Server" entryPointName=http
time="2022-01-31T13:01:50Z" level=info msg="Starting provider *file.Provider"
time="2022-01-31T13:01:50Z" level=debug msg="*file.Provider provider configuration: {\"directory\":\"/rules\",\"watch\":true}"
time="2022-01-31T13:01:50Z" level=info msg="Starting provider *traefik.Provider"
time="2022-01-31T13:01:50Z" level=debug msg="*traefik.Provider provider configuration: {}"
time="2022-01-31T13:01:50Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2022-01-31T13:01:50Z" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {\"Timeout\":4000000000}"
time="2022-01-31T13:01:50Z" level=info msg="Starting provider *docker.Provider"
time="2022-01-31T13:01:50Z" level=debug msg="*docker.Provider provider configuration: {\"watch\":true,\"endpoint\":\"tcp://socket-proxy:2375\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"}"
time="2022-01-31T13:01:50Z" level=info msg="Starting provider *acme.Provider"
time="2022-01-31T13:01:50Z" level=debug msg="*acme.Provider provider configuration: {\"email\":\"pk3000@protonmail.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"./letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"certificatesDuration\":2160,\"dnsChallenge\":{\"provider\":\"namecheap\",\"delayBeforeCheck\":\"10s\"},\"ResolverName\":\"mydnschallenge\",\"store\":{},\"TLSChallengeProvider\":{\"Timeout\":4000000000},\"HTTPChallengeProvider\":{}}"
time="2022-01-31T13:01:50Z" level=debug msg="Attempt to renew certificates \"720h0m0s\" before expiry and check every \"24h0m0s\"" providerName=mydnschallenge.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
time="2022-01-31T13:01:50Z" level=info msg="Testing certificate renew..." providerName=mydnschallenge.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
time="2022-01-31T13:01:50Z" level=debug msg="Configuration received from provider file: {\"http\":{\"middlewares\":{\"whitelist\":{\"ipWhiteList\":{\"sourceRange\":[\"0.0.0.0/0\"]}}}},\"tcp\":{},\"udp\":{},\"tls\":{\"options\":{\"TLSv13\":{\"minVersion\":\"VersionTLS13\",\"cipherSuites\":[\"TLS_AES_256_GCM_SHA384\",\"TLS_CHACHA20_POLY1305_SHA256\"],\"clientAuth\":{},\"sniStrict\":true,\"alpnProtocols\":[\"h2\",\"http/1.1\",\"acme-tls/1\"]},\"default\":{\"minVersion\":\"VersionTLS12\",\"cipherSuites\":[\"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305\",\"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384\"],\"clientAuth\":{},\"sniStrict\":true,\"alpnProtocols\":[\"h2\",\"http/1.1\",\"acme-tls/1\"]}}}}" providerName=file
time="2022-01-31T13:01:50Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"services\":{\"noop\":{}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="2022-01-31T13:01:50Z" level=debug msg="Configuration received from provider mydnschallenge.acme: {\"http\":{},\"tls\":{}}" providerName=mydnschallenge.acme
time="2022-01-31T13:01:50Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2022-01-31T13:01:50Z" level=debug msg="Provider connection established with docker 20.10.12 (API 1.41)" providerName=docker
time="2022-01-31T13:01:50Z" level=debug msg="Filtering disabled container" providerName=docker container=socket-proxy-traefik-9b52c6164e08a4a5e03292de91ba09007207b5183cc91951860e46660f1c42f1
time="2022-01-31T13:01:50Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"http-catchall\":{\"entryPoints\":[\"http\"],\"middlewares\":[\"redirect-to-https\"],\"service\":\"traefik-traefik\",\"rule\":\"hostregexp(`{host:.+}`)\"},\"root\":{\"entryPoints\":[\"https\"],\"middlewares\":[\"redirect-root-to-www\"],\"service\":\"traefik-traefik\",\"rule\":\"host(`memexpk.com`)\",\"tls\":{}}},\"services\":{\"traefik-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.18.0.3:80\"}],\"passHostHeader\":true}}},\"middlewares\":{\"redirect-root-to-www\":{\"redirectRegex\":{\"regex\":\"^https://memexpk\\\\.com/(.*)\",\"replacement\":\"https://www.memexpk.com/${1}\"}},\"redirect-to-https\":{\"redirectScheme\":{\"scheme\":\"https\",\"permanent\":true}}}},\"tcp\":{},\"udp\":{}}" providerName=docker
time="2022-01-31T13:01:50Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2022-01-31T13:01:51Z" level=debug msg="Adding certificate for domain(s) www.memexpk.com"
time="2022-01-31T13:01:51Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2022-01-31T13:01:52Z" level=debug msg="Adding certificate for domain(s) www.memexpk.com"
time="2022-01-31T13:01:52Z" level=debug msg="Creating middleware" routerName=http-catchall@docker serviceName=traefik-traefik middlewareType=Pipelining middlewareName=pipelining entryPointName=http
time="2022-01-31T13:01:52Z" level=debug msg="Creating load-balancer" routerName=http-catchall@docker serviceName=traefik-traefik entryPointName=http
time="2022-01-31T13:01:52Z" level=debug msg="Creating server 0 http://172.18.0.3:80" serverName=0 serviceName=traefik-traefik entryPointName=http routerName=http-catchall@docker
time="2022-01-31T13:01:52Z" level=debug msg="child http://172.18.0.3:80 now UP"
time="2022-01-31T13:01:52Z" level=debug msg="Propagating new UP status"
time="2022-01-31T13:01:52Z" level=debug msg="Added outgoing tracing middleware traefik-traefik" entryPointName=http routerName=http-catchall@docker middlewareName=tracing middlewareType=TracingForwarder
time="2022-01-31T13:01:52Z" level=debug msg="Creating middleware" entryPointName=http middlewareName=redirect-to-https@docker middlewareType=RedirectScheme routerName=http-catchall@docker
time="2022-01-31T13:01:52Z" level=debug msg="Setting up redirection to https " middlewareName=redirect-to-https@docker middlewareType=RedirectScheme routerName=http-catchall@docker entryPointName=http
time="2022-01-31T13:01:52Z" level=debug msg="Adding tracing to middleware" routerName=http-catchall@docker middlewareName=redirect-to-https@docker entryPointName=http
time="2022-01-31T13:01:52Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=http middlewareName=traefik-internal-recovery
time="2022-01-31T13:01:52Z" level=debug msg="Creating middleware" serviceName=traefik-traefik middlewareName=pipelining middlewareType=Pipelining entryPointName=https routerName=root@docker
time="2022-01-31T13:01:52Z" level=debug msg="Creating load-balancer" entryPointName=https routerName=root@docker serviceName=traefik-traefik
time="2022-01-31T13:01:52Z" level=debug msg="Creating server 0 http://172.18.0.3:80" serviceName=traefik-traefik serverName=0 entryPointName=https routerName=root@docker
time="2022-01-31T13:01:52Z" level=debug msg="child http://172.18.0.3:80 now UP"
time="2022-01-31T13:01:52Z" level=debug msg="Propagating new UP status"
time="2022-01-31T13:01:52Z" level=debug msg="Added outgoing tracing middleware traefik-traefik" middlewareName=tracing middlewareType=TracingForwarder entryPointName=https routerName=root@docker
time="2022-01-31T13:01:52Z" level=debug msg="Creating middleware" middlewareType=RedirectRegex middlewareName=redirect-root-to-www@docker entryPointName=https routerName=root@docker
time="2022-01-31T13:01:52Z" level=debug msg="Setting up redirection from ^https://memexpk\\.com/(.*) to https://www.memexpk.com/${1}" routerName=root@docker middlewareType=RedirectRegex middlewareName=redirect-root-to-www@docker entryPointName=https
time="2022-01-31T13:01:52Z" level=debug msg="Adding tracing to middleware" routerName=root@docker middlewareName=redirect-root-to-www@docker entryPointName=https
time="2022-01-31T13:01:52Z" level=debug msg="Creating middleware" entryPointName=https middlewareType=Recovery middlewareName=traefik-internal-recovery
time="2022-01-31T13:01:52Z" level=debug msg="Adding route for memexpk.com with TLS options default" entryPointName=https

**Comment by PLK2** [comment]
My home router is set to forward ports 22, 80, and 443 to my rockpro64's IP. Confirmed they're open using portchecker.co website.

**Comment by BaptisteBdn** [comment]
Hello,

```
time="2022-01-31T12:35:28Z" level=error msg="Unable to obtain ACME certificate for domains "": unable to generate a certificate in ACME provider when no domain is given" routerName=webserver@docker rule="Host(``)" 
```
It looks like traefik cannot find the domain in the webserver label. Can you check it that it is in the `webserver/.env` file ?
