### ISSUE TITLE
Letsencrypt directory vanished from Traefik directory

### ISSUE THREAD

**Issue by PLK2** [BaptisteBdn/docker-selfhosted-apps#4]
Letsencrypt used to be found in here, but no longer?
https://github.com/BaptisteBdn/docker-selfhosted-apps/tree/main/traefik

Don't see it anywhere else.

**Comment by PLK2** [comment]
Or is this created when Traefik runs the first time?
OMG am I that dumb.

**Comment by BaptisteBdn** [comment]
It is indeed created when traefik runs the first time 😉

**Comment by PLK2** [comment]
indeedlydoodly
