### ISSUE TITLE
backup-borg-s3.sh - Gotify stats

### ISSUE THREAD

**Issue by luca-sambuca** [BaptisteBdn/docker-selfhosted-apps#6]
Hi! First of all, thank you for this amazing guide!

I implemented borg and the synch to S3 works. However, I got an error message when it tried to generate the Gotify stats.

In my opinion, line 91 in your backup-borg-s3.sh should be changed to the following:
`AWS_STATS=$(aws s3 ls --profile=${BORG_S3_BACKUP_AWS_PROFILE} --summarize --recursive s3://${BORG_S3_BACKUP_BUCKET} | tail -1 | awk '{ printf "%.3f GB", $3/1024/1024/1024; }')	`

Changing it that way should use the information provided in the .env file.

**Comment by BaptisteBdn** [comment]
Thanks a lot, that's a mistake on my part. I'm glad you are liking the guide !
